### ISSUE TITLE
Q4 (Clean) SIMS POART Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/ICPI-Product-Tracker#15]
Q4 Timeline
- Q4 Clean Data Entry Period (12/1-12/21)
- Datasets become available in Genie (12/21)
- Datasets becomes available on Panorama (1/4)

Q4 Cleaned Checklist:
- [x] Finalize tool [template] in preparation for Q4 cleaned data population (12/17)
- [x] Populate tool (1/7-1/10)
- [x] QA/QC tool (1/11)
- [x] Submit final tool(s) to PEPFAR.net (1/11)

Link to Working folder / Instructions & Templates: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FSIMS%2FWorking%20Folder%2FPOART%20Dashboard%5FWorking&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence

[SIMS_POART Dashboard_Population Instructions_20181218.docx](https://github.com/ICPI/ICPI-Product-Tracker/files/2733115/SIMS_POART.Dashboard_Population.Instructions_20181218.docx)
[Templates.zip](https://github.com/ICPI/ICPI-Product-Tracker/files/2733116/Templates.zip)

**Comment by aknute** [comment]
Population Assignments for Q4/Cleaned:

**OU/REGION | ANALYST**
Angola | Rebecca
Asia Region* | Rebecca
Botswana | Faith
Burundi | Rebecca
Cameroon | Faith
Caribbean Region | Meaghan
Cote d'Ivoire | Faith
Democratic Republic of Congo | Faith
Dominican Republic | Meaghan
Eswatini | Faith
Ethiopia | Rebecca
Ghana | Rebecca
Haiti | Meaghan
Kenya | Audrey
Lesotho | Meaghan
Malawi | Meaghan
Mozambique | Faith
Namibia | Rebecca
Nigeria | Audrey
Rwanda | Rebecca
South Africa | Audrey
South Sudan | Faith
Tanzania | Shaylee
Uganda | Audrey
Ukraine | Rebecca
Vietnam | Faith
Zambia | Faith
Zimbabwe | Rebecca

*Asia Region includes: Asia Regional Program, Burma, Cambodia, Central Asia Region, India, Indonesia, and Papua New Guinea

**Comment by hessionra** [comment]
Hi @aknute I can work on these this week!

**Comment by aknute** [comment]
Great!

________________________________
