### ISSUE TITLE
Q4 Clean Key Populations Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/ICPI-Product-Tracker#20]
Q4 Timeline
- Q4 Clean Data Entry Period (12/1-12/21)
- Datasets become available in Genie (12/21)
- Datasets becomes available on Panorama (1/4)

Q4 Clean Checklist:
- [ ] Finalize tool [template] in preparation for Q4 initial data population (12/17)
- [ ] Populate tool (12/21-1/7)
- [ ] QA/QC tool (1/8)
- [ ] Submit final tool(s) to PEPFAR.net (1/9)

**Comment by hessionra** [comment]
@wvp3 @Yabayabadoo @vanamala-narasimhan @jb3436 checking in on the status of KP? Thank you!

**Comment by hessionra** [comment]
@wvp3 @Yabayabadoo @vanamala-narasimhan @jb3436 Following up on the status of KP-- let me know if it will be ready for today's Huddle release or if there has been a delay. Thank you!

**Comment by wvp3** [comment]
It will be ready for today’s release and we will send you the link shortly.  Thanks.

**Comment by wvp3** [comment]
https://www.pepfar.net/OGAC-HQ/icpi/Products/ICPI%20Approved%20Tools%20(Most%20Current%20Versions)/Key%20Populations%20Dashboard/ICPI_KP%20Tool_FY18Q4_clean_1-10-2019_TWL.xlsx

**Comment by hessionra** [comment]
Thank you, @wvp3 ! I will go ahead and close this ticket and move it to "Huddle Ready" in the product tracker.
