### ISSUE TITLE
Q4 Clean Performance Trends

### ISSUE THREAD

**Issue by hessionra** [ICPI/ICPI-Product-Tracker#27]
Q4 Timeline
- Q4 Clean Data Entry Period (12/1-12/21)
- Datasets become available in Genie (12/21)
- Datasets becomes available on Panorama (1/4)

Q4 Clean Checklist:
- [x] Finalize tool [template] in preparation for Q4 initial data population (12/17)
- [x] Populate tool (12/21-1/7)
- [x] QA/QC tool (1/8)
- [ ] Submit final tool(s) to PEPFAR.net (1/9)

**Comment by hessionra** [comment]
@anu87 please close this ticket and move it to "Huddle Ready" when it is up on SharePoint!

**Comment by hessionra** [comment]
Hi all! @anu87 @MicSherlock @KatieOC @jb3436 Let me know the status of Performance Trends and if it will be ready in time for the Huddle release! If it is not ready, we can put a "read.me" file in the folder letting people know that it will be uploaded shortly. Thank you!

**Comment by KatieOC** [comment]
@anu87 looks like an older version was uploaded. I also sent you an email regarding this. thanks!

**Comment by KatieOC** [comment]
@hessionra I put up a README for posting tomorrow OOB.
