### ISSUE TITLE
HIV_Exposed Infant Dashboard

### ISSUE THREAD

**Issue by KatieOC** [ICPI/ICPI-Product-Tracker#31]
New dashboard for FY18 clean Q4.

**Comment by KatieOC** [comment]
@nmcdavid not sure if you saw my emails but there is one issue on the last tab we need to resolve before I can upload it for the Huddle. thanks!

**Comment by KatieOC** [comment]
@hessionra I have uploaded a README document outlining when the HEI dashboard will be posted.

**Comment by KatieOC** [comment]
global tool uploaded. Pending uploads of site level dashboards but will close this issue.

**Comment by hessionra** [comment]
Q1 Clean Timeline
- Q1 Clean Data Entry Period (3/4-3/22)
- Datasets become available in Genie (3/22)
- Datasets becomes available on Panorama (3/29)

Q1 Clean Checklist:
- [x] Finalize tool [template] in preparation for Q1 clean data population (3/18)
- [x] Populate tool (3/25)
- [x] QA/QC tool (3/27)
- [x] Submit final tool(s) to PEPFAR.net (4/2)

**Comment by hessionra** [comment]
@KatieOC Please let us know if this will be ready for submission on 4/2!

Looping in @jb3436

**Comment by nmcdavid** [comment]
Hi @hessionra - I've populated the tool with clean FY19Q1 data and I'll upload to our working folder in PEPFAR.net. I'm working on QC'ing the tool but would like a second pair of eyes.

**Comment by nmcdavid** [comment]
Also, I'm hoping to complete the site-level dashboards by 3pm tomorrow, latest COB tomorrow.

**Comment by hessionra** [comment]
Great, thank you @nmcdavid !

**Comment by KatieOC** [comment]
initial QC complete, pending a few updates from @nmcdavid

**Comment by KatieOC** [comment]
global posted. will be posting site level shortly.

**Comment by hessionra** [comment]
Thank you @KatieOC and @nmcdavid , great work!
