### ISSUE TITLE
Q1 Entry Prevention Trends Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/ICPI-Product-Tracker#36]
Q1 Timeline
- Q1 Initial Data Entry Period (1/7-2/15)
- Datasets become available in Genie (2/15)
- Datasets becomes available on Panorama (2/22)

Q1 Entry Checklist:
- [ ] Finalize tool [template] in preparation for Q1 initial data population (2/11)
- [ ] Populate tool (2/18)
- [ ] QA/QC tool (2/20)
- [ ] Submit final tool(s) to PEPFAR.net (2/26)

**Comment by kimisatoPC** [comment]
This tool has been retired.
