### ISSUE TITLE
Q4 (Initial) OVC Dashboard

### ISSUE THREAD

**Issue by hessionra** [ICPI/ICPI-Product-Tracker#4]
GitHub location: https://github.com/ICPI/Prevention-Cluster

Includes [script](https://github.com/ICPI/Prevention-Cluster/tree/master/OVC) for tool updating.

**Comment by hessionra** [comment]
Q4 Initial Checklist:

- [x] Q4 Initial Data Entry Open (10/1)
- [x] Analysts finalize dashboards in preparation for Q4 initial data population (11/12)
- [x] Q4 Initial Data Entry Close (11/15)
- [x] Datasets become available in Genie (11/15)
- [x] Begin Dashboard Population (11/16)
- [x] Dashboard QC (11/19)

**Comment by shapaklyak** [comment]
Currently working on updating the R script for Genie data pull Q4 
FYI @hessionra @kimisatoPC @erinschelar

**Comment by shapaklyak** [comment]
R Script updated and OVC Dashboard Ready for QC. Dashboard & QC Template can be found on [pepfar.net ](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FPending%20QC%2FFY18Q4%20Unclean&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

**Comment by shapaklyak** [comment]
Currently in QC - one OU passed, waiting on additional analyst review

**Comment by shapaklyak** [comment]
QC passed Tanzania & South Africa across all tabs. QC documentation can be found on [pepfar.net](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FOVC%2FPending%20QC%2FFY18Q4%20Unclean&FolderCTID=0x01200080CC6F83D1766F4D9E3497D4529EC74A&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)

**Comment by shapaklyak** [comment]
FY18Q4 initial OVC Dashboard approved for use posted in[ ICPI Products Library](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FICPI%20Approved%20Tools%20%28Most%20Current%20Versions%29%2FOVC&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence)
