### ISSUE TITLE
Q4 (Initial) Prevention Trend Tool

### ISSUE THREAD

**Issue by hessionra** [ICPI/ICPI-Product-Tracker#7]
GitHub location: https://github.com/ICPI/Prevention-Cluster

Includes [script ](https://github.com/ICPI/Prevention-Cluster/tree/master/Cross-cutting)for tool updating.

**Comment by hessionra** [comment]
Q4 Initial Checklist:

- [x] Q4 Initial Data Entry Open (10/1)
- [x] Analysts finalize dashboards in preparation for Q4 initial data population (11/12)
- [x] Q4 Initial Data Entry Close (11/15)
- [x] Datasets become available in Genie (11/15)
- [x] Begin Dashboard Population (11/16)
- [x] Dashboard QC (11/19)

**Comment by kimisatoPC** [comment]
I attempted to update the R code to use the Genie output, but since Rwanda and Eswatini are at one level below the PSNU, I cannot update the dashboard. Spoke with Abe and the DREAMS MSD will be available on 11/19 and I will plan to update the tool by 11/21.

**Comment by kimisatoPC** [comment]
@shapaklya [Prevention Trends Tool](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FCross%2DCutting%2FPrevention%20Trend%20Tool&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D) has been populated and is ready for [QC Protocol posted here on SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FPrevention%2FWorking%20Folder%2FCross%2DCutting%2FQC%20Materials&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by hessionra** [comment]
Submitted to ICPI@state.gov on 11/21.
